server:
  port: 8001

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

hystrix:
  commond:
    default:
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
