server:
  port: 4002

zuul:
  prefix: /v1
  routes:
    ribbonApi:
      path: /ribbon1/**
      serviceId: cloud-consumer-ribbon
    feignApi:
      path: /feign1/**
      serviceId: cloud-consumer-feign

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000