server:
  port: 4001

zuul:
  # prefix: /v1
  routes:
    ribbonApi:
      path: /ribbon/**
      serviceId: cloud-consumer-ribbon
    feignApi:
      path: /feign/**
      serviceId: cloud-consumer-feign

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000